name: push main

on:
  push:
    branches:
      - main

permissions:
    contents: write
    pull-requests: write

jobs:
  on_push_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
