name: Remind NPM_TOKEN
on:
  schedule:
    # 2/28 @ every year
    - cron:  "0 0 28 2 *"

jobs:
  create_issue:
    name: Remind NPM_TOKEN
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create sync issue
        uses: imjohnbo/issue-bot@v3.4
        with:
          assignees: "kyo-ago"
          labels: "Type: Release"
          title: "[Action Required] env.NPM_TOKEN will be expired"
          body: |
            `NPM_TOKEN` will be expired.
            Please update `NPM_TOKEN` of GitHub Actions.
            
            - Create new granular-access-tokens for check-github-actions-node-version
            - Update https://github.com/kyo-ago/check-github-actions-node-version/settings/secrets/actions/NPM_TOKEN
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
